/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VrDemoRouteImport } from './routes/vr-demo'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VrDemoRoute = VrDemoRouteImport.update({
  id: '/vr-demo',
  path: '/vr-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/solution': typeof SolutionRoute
  '/vr-demo': typeof VrDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/solution': typeof SolutionRoute
  '/vr-demo': typeof VrDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/solution': typeof SolutionRoute
  '/vr-demo': typeof VrDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impact'
    | '/partnerships'
    | '/solution'
    | '/vr-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/impact' | '/partnerships' | '/solution' | '/vr-demo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impact'
    | '/partnerships'
    | '/solution'
    | '/vr-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpactRoute: typeof ImpactRoute
  PartnershipsRoute: typeof PartnershipsRoute
  SolutionRoute: typeof SolutionRoute
  VrDemoRoute: typeof VrDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vr-demo': {
      id: '/vr-demo'
      path: '/vr-demo'
      fullPath: '/vr-demo'
      preLoaderRoute: typeof VrDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpactRoute: ImpactRoute,
  PartnershipsRoute: PartnershipsRoute,
  SolutionRoute: SolutionRoute,
  VrDemoRoute: VrDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
